// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default {
  schemaPath: './prisma/schema.prisma',
  migrationsPath: './prisma/migrations',
};
